version: "3.8"

services:
  Cache:
    image: redis:bullseye
    container_name: redis
    hostname: redis
    restart: always
    #command: redis-server --requirepass ${REDIS-PASS} --masteruser ${REDIS-USER}
    command: redis-server 
    environment:
      - REDIS-PASS=123
      - REDIS-USER=Camilo
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - host

  RedisCommander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis
      - PORT=8085
    ports:
      - "8085:8085"
    expose:
      - "8085"
    networks:
      - host