version: "3.8"

services:
  Db:
    image: mysql:5.7
    container_name: ${DB_HOST_NAME}
    hostname: ${DB_HOST_NAME}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=ZUP
      # You don't have to use root, but you can if you like
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - host

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    depends_on:
      - Db
    environment:
      PMA_HOST: ${DB_HOST_NAME}
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - host