version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - host

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8086:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: user #web access
      ME_CONFIG_BASICAUTH_PASSWORD: password #web password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    networks:
      - host